// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlBRnGPiqu3-8DLnFTDPb9LOZQ6R-6rs4',
    appId: '1:1051211273003:web:0e6b4536fea7e78e9b6b6e',
    messagingSenderId: '1051211273003',
    projectId: 'dharati-63d5e',
    authDomain: 'dharati-63d5e.firebaseapp.com',
    storageBucket: 'dharati-63d5e.appspot.com',
    measurementId: 'G-RT2LBMCKXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPvBkm5JdHrnIJRaaQk33Ed2jJxIZYt9s',
    appId: '1:1051211273003:android:6e21d8dcb7c457c99b6b6e',
    messagingSenderId: '1051211273003',
    projectId: 'dharati-63d5e',
    storageBucket: 'dharati-63d5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90xkoQIsJoJponKMF-rm-kXr5QkPmvBo',
    appId: '1:1051211273003:ios:c186ff06fc65b55c9b6b6e',
    messagingSenderId: '1051211273003',
    projectId: 'dharati-63d5e',
    storageBucket: 'dharati-63d5e.appspot.com',
    androidClientId: '1051211273003-9jt6n6uv5repbcrfu5a1ib5i2fec13tb.apps.googleusercontent.com',
    iosClientId: '1051211273003-osb6spd2vevpd81icve5qfto4ppj9qc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dharati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC90xkoQIsJoJponKMF-rm-kXr5QkPmvBo',
    appId: '1:1051211273003:ios:c186ff06fc65b55c9b6b6e',
    messagingSenderId: '1051211273003',
    projectId: 'dharati-63d5e',
    storageBucket: 'dharati-63d5e.appspot.com',
    androidClientId: '1051211273003-9jt6n6uv5repbcrfu5a1ib5i2fec13tb.apps.googleusercontent.com',
    iosClientId: '1051211273003-osb6spd2vevpd81icve5qfto4ppj9qc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dharati',
  );
}
